name: Node.js CI

on:
  push:
    branches: ["main"]
    paths:
      - "cli/**"
      - "site/**"
  pull_request:
    branches: ["main"]
    paths:
      - "cli/**"
      - "site/**"

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      cli_changed: ${{ steps.set_env.outputs.cli_changed }}
      site_changed: ${{ steps.set_env.outputs.site_changed }}
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 0

      - name: Check for CLI and Site changes
        id: set_env
        run: |
          echo "Checking changed files"
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE_SHA="${{ github.event.pull_request.base.sha }}"
            HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          else
            BASE_SHA="${{ github.event.before }}"
            HEAD_SHA="${{ github.sha }}"
          fi
          CLI_CHANGED=$(git diff --name-only $BASE_SHA $HEAD_SHA | grep 'cli/' | wc -l)
          SITE_CHANGED=$(git diff --name-only $BASE_SHA $HEAD_SHA | grep 'site/' | wc -l)
          if [ $CLI_CHANGED -gt 0 ]; then
            echo "cli_changed=true" >> $GITHUB_ENV
          else
            echo "cli_changed=false" >> $GITHUB_ENV
          fi
          if [ $SITE_CHANGED -gt 0 ]; then
            echo "site_changed=true" >> $GITHUB_ENV
          else
            echo "site_changed=false" >> $GITHUB_ENV
          fi

  build_and_test_cli:
    runs-on: ubuntu-latest
    needs: check_changes
    if: needs.check_changes.outputs.cli_changed == 'true'
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v3.2.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Install CLI dependencies 📦
        run: npm ci --no-audit -w cli

      - name: Build CLI 🛠️
        run: npm run build -w cli

      - name: Test CLI 🧪
        run: npm test -w cli

  build_and_test_site:
    runs-on: ubuntu-latest
    needs: check_changes
    if: needs.check_changes.outputs.site_changed == 'true'
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v3.2.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Install site dependencies 📦
        run: npm ci --no-audit -w site

      - name: Build site 🛠️
        run: npm run build -w site

      - name: Test site 🧪
        run: npm test -w site
